# Generated by Django 3.2.3 on 2021-05-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image',
            field=models.ImageField(default='null', upload_to='apply_img/'),
        ),
    ]
